### ISSUE TITLE
Can not edit variable that is too long

### ISSUE THREAD

**Issue by silverqx** [Bill-Stewart/editenv#1]
My path variable is so long that it does not fit into the visible screen, I have to scroll up to see the beginning, it is long around 3 scollbacks.

I'm not able to go with the cursor out of the current scrollback, I can scroll with mouse up, but when I press `HOME` or `LEFT` then the editenv scrolls the buffer to the bottom.

I hope that it is understandable. :)

Even `-b` param did not help, used command was `editenv -b PATH`

**Comment by silverqx** [comment]
I checked now and the length of my env PATH var is 7260 chars and I can edit only *last* 3815 chars (around).

**Comment by Bill-Stewart** [comment]
I can't reproduce. I set an environment variable of 7264 characters and I can edit it. (The line editor can't go backwards farther than there is room in the vertical scroll.)

**Comment by silverqx** [comment]
I have create gif to demonstrate the problem:
![out](https://user-images.githubusercontent.com/86900/138726697-b30af7f2-dd12-4fa5-8a56-af1cce4563e8.gif)

**Comment by Bill-Stewart** [comment]
The program uses the standard Windows console APIs; it looks like you are using a different terminal interface than the Windows console. It would appear that is not supported.

**Comment by silverqx** [comment]
I'm using latest Windows Terminal with PSReadLine 2.1.0.

**Comment by silverqx** [comment]
But now I have tried and I can reproduce it on classic cmd.exe too.

**Comment by Bill-Stewart** [comment]
I can't reproduce when using a standard windows console that has a big enough vertical scroll.

**Comment by silverqx** [comment]
It looks absolutely the same like in the gif above when the env. variable is longer/bigger than the currently visible screen buffer, then it is not possible to move to the beginning, I can edit only the visible part, what is outside is unavailable.

**Comment by Bill-Stewart** [comment]
Make sure the console session has a sufficient number of lines (right-click title bar, **Properties**, **Layout** tab, **Height** option).

**Comment by silverqx** [comment]
omg you are right, I was absolutely sure that I have it set to a big number, but windows reset it during update or something, it was 34 now, so in cmd it works normally, but I'm not using cmd around 5 years 😀
Do you have any plan to add WindowsTerminal support, it looks like they use some new API or something.

**Comment by Bill-Stewart** [comment]
I will check into this but it may take a while.

**Comment by silverqx** [comment]
That is not a problem, we have time and time 🙂, WT has historySize 9001 by default.

I have a feeling that on WT will be needed to use [ScrollConsoleScreenBuffer](https://docs.microsoft.com/en-us/windows/console/scrolling-a-screen-buffer-s-contents) function, I looked at this a few weeks ago because I needed it for something else.

**Comment by Bill-Stewart** [comment]
Seems this is a known issue in Windows Terminal:

https://github.com/microsoft/terminal/issues/10191

So I really don't think there's anything to fix here.

**Comment by silverqx** [comment]
It looks like exactly the same issue and now I remembered why I looked at ScrollConsoleScreenBuffer function a few weeks ago, I tried to fix content scrolling in vim in WT that is exactly the same issue like this and like microsoft/terminal#10191.

**Comment by Bill-Stewart** [comment]
Just released 1.6.1 which checks maximum input length.

**Comment by silverqx** [comment]
I would try it, but only source files are on Release page, can you upload compiled version?

**Comment by silverqx** [comment]
Ok, I see it, I have looked to the latest commit and it only detects max. input length and print error message, anyway I suppose that problem still exists?

**Comment by Bill-Stewart** [comment]
Correct, see updated doc. Currently the only fix for your case is to shorten your path or expand your terminal window (or both) because WT won't let us move the cursor backwards into the scrollback area. Alternatively you could use a short script that dumps your path to a file, edit, and then write it back to the environment; e.g. (PowerShell):

    $tempFileName = New-TemporaryFile
    $env:Path | Out-File $tempFIleName
    notepad $tempFileName
    $env:Path = Get-Content $tempFileName
    Remove-Item $tempFileName

...or something similar.

**Comment by silverqx** [comment]
Yeah, I have read that updated docs, thx for the reply, so I understood it correctly, you have spent a lot of effort to info a user about long env. vars., I appreciate it, thx

I'm currently using this, eg:
```
$env:Path = "E:\Qt\6.0.0\msvc2019_64\bin;" + $env:Path
```

I searched a lot to find something like editenv, but I didn't find any solution, editenv is good, but has this problem. For now, I will stick with the command above.

**Comment by silverqx** [comment]
And for shorter env. vars I will use editenv

**Comment by Bill-Stewart** [comment]
FWIW I doubt you really need that many directories in your path. But whatever works for you.

**Comment by silverqx** [comment]
I have only dirs I really need, I manage my PATH env. var. but is much longer after I call `vcvars64` from visual studio, without that my PATH fits into a half-screen buffer, maybe little longer 😂
