### ISSUE TITLE
ERROR "Current and parent process must both be 32-bit or both 64-bit"

### ISSUE THREAD

**Issue by mdalacu** [Bill-Stewart/editenv#2]
Hi. Can you tell me how i can bypass this error?
`Current and parent process must both be 32-bit or both 64-bit (216)`
In console if I launch editenv without any parameters it displays help without any error But if I use --prompt it gives me the above error.
The program is compiled with fpc 32.bit and is running insede win10 64 bit. 
If i start cmd.exe from sysWOW64 folder then the program works in full without any errors but the with the defauld cmd.exe will not.
Thanks.

**Comment by Bill-Stewart** [comment]
I not able to reproduce this. Please try the `editenv.exe` files in the latest download version.
